### ISSUE TITLE
On Volla Phone 22, Morph Browser seems to have trouble displaying a specific website

### ISSUE THREAD

**Issue by pnguyen9** [HelloVolla/ubuntu-touch-beta-tests#143]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

Ubuntu 16.04 2022-08-18/2

### Describe the bug

This morning, I tried accessing the following website to download a document I needed: https://eden.fftir.org/

The website displays properly on my computer on Firefox but doesn't seem to load on Morph Browser on Ubuntu Touch. After the loading bar fills up, the page remains blank. I'm not entirely sure if the problem comes from the website, or the browser lacking some kind of feature.

### Steps to reproduce the bug

- Open Morph Browser.
- Type the following into the URL bar: eden.fftir.org.
- Confirm.
- The page will load, and once it's done, it remains blank.

### Expected behaviour

The page should be loading up and showing a login page.

**Comment by JamiKettunen** [comment]
Hey, things like this make sense to first report to the upstream repository where they're seen properly, i.e. in this case https://gitlab.com/ubports/development/core/morph-browser/-/issues, and later an issue created here in case it turns out to be some device specific issue.

Please do let me know if this issue should be re-opened later!
