### ISSUE TITLE
After fresh Ubuntu touch install SIM card is not recognised

### ISSUE THREAD

**Issue by tihos** [HelloVolla/ubuntu-touch-beta-tests#152]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

16.04

### Describe the bug

Hi,
I reinstalled my Volla 22 with Ubuntu touch and now my phone cannot detect any SIM card. Tried to install Volla OS but it is the same - SIM cards are not detected.
Can someone help me, please?
Thanks.

### Steps to reproduce the bug

1. Fresh install of ubuntu touch from Ubuntu installer
2. All function well but the SIM cards - not recognised 
3. Tried to install again Volla OS but the issue still persists 

### Expected behaviour

I am expecting the phone to functions as a phone. Now my Volla phone without SIM card is not functional

**Comment by JamiKettunen** [comment]
Which update channel is the device on, Development? RC? Stable? You chose this during the UBports installer process as well:
![image](https://user-images.githubusercontent.com/47358222/202897287-acd0887f-4ee4-4b36-a26a-5271d4e88fd2.png)

Also do you see any SIM card icons in the top bar / connectivity indicator or SIM card settings in system settings itself?

**Comment by tihos** [comment]
Hi,
It is on 16.04/stable.
No SIM cards icons neither on the top bar nor in the SIM card settings. Just not any SIM cards. Tried different cards but no joy.

**Comment by JamiKettunen** [comment]
As you say "I reinstalled my Volla 22 with Ubuntu touch" I assume you had Volla OS installed before this started happening and cellular functions worked normally?

**Comment by tihos** [comment]
Yes, sure. I have ordered it with Volla OS and installed Ubuntu touch as a dual boot option. But I was playing with installing different channels in Ubuntu touch and somehow crashed the setup and did not want to boot any OS. Then I started to play with ubports installer. Installed Ubuntu touch (after 3 unsuccessful tries). All was fine but the SIM cards issue. After that I tried to install Volla OS again through ubports installer and it was fine but again any SIM cards was detected - not at all.

**Comment by tihos** [comment]
BTW I saw your post here but realised that it is for Volla but not for Volla 22. Tried and was not successful.

**Comment by JamiKettunen** [comment]
What do you mean by that? Which post? What is your device model exactly? I'm a bit confused now, do you have the original Volla Phone (2020)?

**Comment by tihos** [comment]
I meant here:
"[yggdrasil] SIM card not detected when using Volla OS but is detected on Ubuntu Touch #1612"

**Comment by tihos** [comment]
I suppose the problem is with "NVDATA" partition

**Comment by wurzer** [comment]
This issue is not reproducible. Please open a ticket at volla.online/en/support and add following information:

* Which release channel and software version are you using? 16.04 is not a release version of Ubuntu Touch. Please note, that you should only use the stable release channel. Developer releases are automatically build and may have broken features.
* Are you using Ubuntu Touch as a first or second operating system on your device? 
* If you are using Ubuntu Touch as a first operating system: How did you install it?
* Are the IMEI numbers visible in the info section of the device settings? I they are lost, something went wrong during the installation process and the device can't connect to the cellular network.
