### ISSUE TITLE
[20.04] Hotspot-function not usable

### ISSUE THREAD

**Issue by buchnerh** [HelloVolla/ubuntu-touch-beta-tests#162]
### Is this a new report?

Yes

### Device model

Volla Phone (2020)

### OS version

20.04 devel R403

### Describe the bug

Hotspot can be configured and activated, but the device which wants to connect to the hotspot, doesn't get an IP-address. 

### Steps to reproduce the bug

1. Configure the hotspot-feature with a password
2. Take another device and try to connect to connect to the hotspot
3. Enter Password

### Expected behaviour

After entering the password the device should get an IP from the hotspot and can use the internet-connection from the hotspot.

**Comment by JamiKettunen** [comment]
Seems some other non-Volla devices (namely Samsung Galaxy S7) are also having very similar problems, upstream issue: https://gitlab.com/ubports/development/core/packaging/network-manager/-/issues/5

**Comment by JamiKettunen** [comment]
As a part of starting to move over [the device specific issues](https://gitlab.com/ubports/porting/reference-device-ports/android9/volla-phone/volla-yggdrasil/-/issues) to the UBports GitLab for 20.04 and up I'll close this since a matching issue report now exists, please follow https://gitlab.com/ubports/porting/reference-device-ports/android9/volla-phone/volla-yggdrasil/-/issues/3 for further progress ^^
