### ISSUE TITLE
[20.04] Volla Phone 1st Gen network quick settings: third entry in SIM list (SIM 3)

### ISSUE THREAD

**Issue by Bsoupe** [HelloVolla/ubuntu-touch-beta-tests#164]
### Is this a new report?

Yes

### Device model

Volla Phone (2020)

### OS version

20.04 (r422)

### Describe the bug

After update from 16.04 to 20.04 the network menu shows a path under SIM2 its /hfp/org/bluez/hci0/dev_38_78_62_4D_..
![UT-Focal-3SIM](https://user-images.githubusercontent.com/71604971/226037501-a3215402-5163-435f-b6b7-169f6eb7e46b.jpg)

### Steps to reproduce the bug

Update from 16.04 to 20.04 

### Expected behaviour

No entry between SIM 2 and Hotspot.

**Comment by JamiKettunen** [comment]
Not a device specific issue as can be seen on other devices too, upstream issue: https://gitlab.com/ubports/development/core/lomiri-indicator-network/-/issues/100

**Comment by JamiKettunen** [comment]
As a part of starting to move over [the device specific issues](https://gitlab.com/ubports/porting/reference-device-ports/android9/volla-phone/volla-yggdrasil/-/issues) to the UBports GitLab for 20.04 and up I'll close this since an upstream issue report already exists, please follow that for further progress ^^
