### ISSUE TITLE
SIM card paralyzes mobile communications on Volla X23

### ISSUE THREAD

**Issue by franco-bez** [HelloVolla/ubuntu-touch-beta-tests#167]
in my VollaPhone X23 I use two SIM cards.
Both of them work fine on the phone when running on the Android based VollaOS.
On Ubuntu Touch Focal however one of my SIM Cards seems to paralyse the whole mobile communication subsystem.
The X23 is a dual SIM device, the problem occurs on either SIM slot, no matter if used as the only SIM or in combination with the other SIM card in the other slot.
Using my other SIM card alone works fine in either slot. So the problem is triggered by SIM card.

see also 
https://gitlab.com/ubports/porting/reference-device-ports/halium12/volla-x23/volla-vidofnir/-/issues/11

**Comment by franco-bez** [comment]
Am I the only one affected?
The only one equipped with a SIM card that confuses Ubuntu Touch so much that telephony, SMS, and mobile data gets disabled completely?

**Comment by RinkebyDanceKids** [comment]
I run dual boot UT, that is segnificant different in bugs. But I cant even get one sim card right. No mobile internet.

**Comment by JamiKettunen** [comment]
Sorry for the late response, there's a new update channel for testing containing new firmware which fixes eSIM support (still has to be activated from Android side atm) for example, perhaps that will help?

To test it you'll want to be on the very latest 20.04 devel build first, and then switch to the hidden staging update channel via either UBports installer or on-device / `adb shell`:
```
sudo system-image-cli --switch 20.04/arm64/android9plus/staging -v
```
If you switch to staging **before** first being on latest devel build you'll soft-brick the device since previous versions of the UBports recovery had incorrect fstab entries causing the upgraded firmware to be partially flashed to only a few partitions.

This response was copied from https://gitlab.com/ubports/porting/reference-device-ports/halium12/volla-x23/volla-vidofnir/-/issues/11#note_1733295257, let's try to continue discussions there if possible as all port-specific bugs since 20.04 should be submitted in their respective repos (or https://gitlab.com/ubports/ubuntu-touch/-/issues from where it can later be moved to any individual repos under UT gitlab as seen fit)

I should note that if you're using UT as a secondary system via multiboot this way of updating won't work (and in fact would replace VollaOS if UBports installer is used for UT installation), you'll get the update later when deemed stable enough which should hopefully be soon :)
