### ISSUE TITLE
BACK BUTTON disappears when choosing Ringtones and playing sound in settings

### ISSUE THREAD

**Issue by CubedApple** [HelloVolla/ubuntu-touch-beta-tests#181]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 (OTA-4)

### Describe the bug

I was trying to choose ringtones and message tones for my Volla Phone 22 and noticed that when I play a sound, the back button disappears. This prompts me to then close the app, and re-open again. 

Also, it seems one time there was an overlap in sound. Supposedly, the first sound would end when I interrupt by clicking on a different sound. But that is not the case. I noticed it happened at the same time as the back button disappearance bug above.

### Steps to reproduce the bug

1. Go to Settings
2. Go to Sound
3. Click on Ringtone (or Message Sound)
4. Click on ANY sound
5. You will notice the back button disappear

### Expected behaviour

The BACK BUTTON should NOT disappear at all.

**Comment by wurzer** [comment]
Should be reported to UBports

**Comment by CubedApple** [comment]
> Should be reported to UBports

Hi can you please point me to the right direction? I'm not sure where to put this. Thanks

**Comment by JamiKettunen** [comment]
@CubedApple https://gitlab.com/ubports/development/core/lomiri-system-settings/-/issues would be for the settings app itself anyway, probably good enough to create it there and have it moved elsewhere by a developer since I think this may be a toolkit level issue: I've seen dissappearing back button in other places too like file picker upon previewing image and similar stuff
