### ISSUE TITLE
"Audio out" has frequent dropouts

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#33]
The Audio out of the vollaphone has frequent dropouts.
I tested mp3 Musik in 16bit/192 khz with a headphone.
It is like listening to an old vinyl record.
My be the onboard audio chip is still disturbed by inner electronic interferences.
No clean musik can be enjoyed actually.
Ubuntu  version 16.04 (2020-08-11)

**Comment by wurzer** [comment]
I can't reproduce this issue. Maybe you can provide an example file.

**Comment by Stevie00911** [comment]
I have recorded an example file with a simple strings sound.
The file is 3:30 minutes and I have counted 50 dropouts, see attached zip/mp3 file.
Ubuntu version 16.04 (2020-09-06)

[Vollaphone - Audio out - Strings Stereo 3 min.zip](https://github.com/HelloVolla/ubuntu-touch-beta-tests/files/5179616/Vollaphone.-.Audio.out.-.Strings.Stereo.3.min.zip)

**Comment by Stevie00911** [comment]
The dropouts are more heavy and frequent by listening to a .mp4 video file via the media player.
Ubuntu version 16.04. (2020-09-23) developer

**Comment by TellingBerto** [comment]
Same here. If I generate a single (clean) tone here:
https://www.szynalski.com/tone-generator/ 

I get cracks while the tone is played.

1. A "cr" is remarkable when change the volume with the volume hardware button.
2. A "cr" is remarkable when change the volume with the volume +/- provided by the website on the screen.
Not checked with a headphones because I expect a "cr" as well, and with in-ear headphones it does not make fun.

Issue also appear while playing a mp3 file with UT music player.

Ubuntu version 16.04 (2020-09-26), channel: devel

**Comment by Stevie00911** [comment]
In which release will the Audio dropouts be fixed?

**Comment by Stevie00911** [comment]
Ubuntu 16.04 (2020-W44) release candidate:
Well done, the Audiodropouts are gone.
Thank you so much :-)
