### ISSUE TITLE
/etc/hosts does not survive a reboot

### ISSUE THREAD

**Issue by xcvb85** [HelloVolla/ubuntu-touch-beta-tests#58]
"mount -o remount,rw /" fails because root filesystem is write protected. This command is required by uAdBlock.

**Comment by JamiKettunen** [comment]
The following works perfectly fine on Terminal/SSH/ADB shell for me on Development channel build `2020-10-14/2`:
```bash
sudo mount -o remount,rw /
```
Could you attach a screenshot of the error happening? If it happens in-app, you should inform the developer since there's likely nothing we can do to fix it. This is more of a place for port-specific issues.

**Comment by xcvb85** [comment]
Yes, you are right. This is not the reason why uAdBlock doesn't work. For some reason /etc/hosts cannot be modified, which is not the case on my Nexus 4.

**Comment by xcvb85** [comment]
What i originally wanted to say is that uAdBlock does not work because /etc/hosts is constantly overwritten. At least it does not survive a reboot.

**Comment by JamiKettunen** [comment]
@xcvb85 I just tested editing `/etc/hosts` manually after remounting `/` as `rw` and the changes persisted across a reboot; I also tested uAdBlock after pressing `Set new lists`, checked `wc -l /etc/hosts`, rebooted and the lines persisted after multiple tries and shutdowns.
The changes to `/etc/hosts` even persisted across an upgrade on devel channel in my case; I'm unsure what would be clearing the changes to the file on your end.

**Comment by xcvb85** [comment]
Issue is solved in latest RC (W50). Thank you very much!
