### ISSUE TITLE
No rotation reading 

### ISSUE THREAD

**Issue by Blackoverflow** [HelloVolla/ubuntu-touch-beta-tests#74]
**Details about installed OS version**
Ubuntu Touch OTA-14

**Describe the bug**
The app "SensorStatus" doesn't report readings for the rotation sensor.
This also impedes the controls in "Neverball".

**Steps to reproduce the bug**
*SensorStatus*
1. Install SensorStatus
2. Open SensorStatus
3. Open the menu item "Rotation"
4. See no readings

*Neverball*
1. Install Neverball
2. Open Neverball
3. Start any level
4. Don't be able to tilt the floor

**Expected behavior**
Getting rotation readings.
The accelerometer reports readings. Therefore, calculating the rotation should be possible.

Of cause, the apps could also calculate the orientation for themselves. "Stellarium" seems to do that.

**Comment by JamiKettunen** [comment]
As https://open-store.io/app/neverball.abmyii states: `Note: These games currently don't work on Halium 9 devices due to sensors not being read ...` which would make it an issue on all Android 9 HAL based Ubuntu Touch ports and not just a Volla Phone specific one; I think we'll just have to wait until the developer fixes the issue (or if you/someone knows how to fix it could ).
Also I'm not sure what this sensor is exactly meant to report when the acceleration, gyroscope and orientation sensors already give readings in SensorStatus.

**Comment by abmyii** [comment]
Neverball 1.6.1.0 (released today) should now work on Halium 9 devices, though if the sensors aren't being read by SensorStatus then there is likely another underlying issue related to the device/OS. I had the same issue (sensors not being read) on my OnePlus One (bacon) on the `halium-devel` stream, which I fixed by switching to the `Development` stream.
