### ISSUE TITLE
Device sometimes reboots while Teleports is used

### ISSUE THREAD

**Issue by Bsoupe** [HelloVolla/ubuntu-touch-beta-tests#82]
**Details about installed OS version**
OTA-14 stable

**Describe the bug**
Device sometimes reboots while Teleports is in use. Mostly if using functions like answering or editing a message.

**Steps to reproduce the bug**
(The following is an example:)
1. Go to Teleports
2. Use it any longer and do some special
3. somtimes it happens that the device is rebooting 

**Expected behavior**
No reboots without reason.

**Comment by JamiKettunen** [comment]
Does "rebooting" here mean Ubuntu Touch logo coming back onto screen, or the Volla logo? If it's the Ubuntu logo, this could be a dulpicate of #31 but I can't really say for sure since the details on that issue are really descriptive.
Generally this happens when the device runs out of usable system memory and for some reason decides to kill the Lomiri UI instead of something not necessarily needed; this probably still needs deeper investigation as in my eyes it really seems like there  is a massive memory leak somewhere.

**Comment by JamiKettunen** [comment]
As I haven't heard back from you for three months I'll go ahead and close this. Please do comment again / create a new issue if the above one I linked doesn't match your problem! Otherwise if no other apps cause a "device reboot" I recommend reporting about it on [the Teleports bug tracker](https://gitlab.com/ubports/apps/teleports/-/issues) instead.
